name: Build TikTokConverter.app

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniforge (Conda)
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: "latest"
          auto-update-conda: true

      - name: Create & activate Conda env
        run: |
          # initialize conda in this shell
          source "${CONDA}/etc/profile.d/conda.sh"
          # creează un mediu care include Python+tkinter+ffmpeg
          conda create -y -n build-env python=3.11 tcltk=8.6 ffmpeg
          conda activate build-env

      - name: Install Python deps
        run: |
          conda activate build-env
          pip install --upgrade pip
          pip install moviepy pyinstaller

      - name: Build .app with PyInstaller
        run: |
          conda activate build-env
          pyinstaller \
            --windowed \
            --name TikTokConverter \
            --add-binary "$(which ffmpeg):ffmpeg" \
            --hidden-import moviepy.editor \
            --hidden-import moviepy.video.fx.all \
            --hidden-import imageio_ffmpeg \
            main.py

      - name: Zip TikTokConverter.app
        run: |
          cd dist
          zip -r TikTokConverter.app.zip TikTokConverter.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TikTokConverter.app
          path: dist/TikTokConverter.app.zip
