name: Build TikTokConverter.app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout TikTokConverter repo
      uses: actions/checkout@v3

    - name: Debug: list repo contents
      run: ls -R .

    - name: Configure Python 3.11 environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install MoviePy & py2app
      run: |
        python -m pip install --upgrade pip
        pip install moviepy py2app

    - name: Homebrew: install ffmpeg
      run: brew install ffmpeg

    - name: Run py2app to package .app
      run: python3 setup.py py2app

    - name: Zip TikTokConverter.app
      run: |
        cd dist
        zip -r TikTokConverter.app.zip TikTokConverter.app

    - name: Upload TikTokConverter.app.zip
      uses: actions/upload-artifact@v4
      with:
        name: TikTokConverter.app
        path: dist/TikTokConverter.app.zip
