name: Build TikTokConverter.app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Homebrew Python + deps
        run: |
          brew update
          brew install python tcl-tk ffmpeg
          # pune brew-python (cu Framework) în faţă în PATH
          echo "$(brew --prefix)/bin" >> $GITHUB_PATH

      - name: Install py2app & MoviePy
        run: |
          python3 -m pip install --upgrade pip
          pip3 install py2app moviepy

      - name: Build standalone .app
        run: |
          python3 setup.py py2app --standalone

      - name: Code-sign .app ad-hoc
        run: |
          codesign --force --deep --sign - dist/TikTokConverter.app

      - name: Create quarantine-free ZIP
        run: |
          ditto -c -k --sequesterRsrc --keepParent \
            dist/TikTokConverter.app TikTokConverter.app.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TikTokConverter.app
          path: TikTokConverter.app.zip
