name: Build TikTokConverter.app

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.11'
          auto-update-conda: true

      - name: Create Conda env & install Python deps
        run: |
          conda create -y -n build-env python=3.11 tcl-tk pip
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate build-env
          pip install --upgrade pip
          pip install moviepy pyinstaller

      - name: Install FFmpeg
        run: brew install ffmpeg

      - name: Build .app with PyInstaller
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate build-env
          pyinstaller \
            --windowed \
            --name TikTokConverter \
            --add-binary "$(which ffmpeg):ffmpeg" \
            --hidden-import moviepy.editor \
            --hidden-import moviepy.video.fx.all \
            --hidden-import imageio_ffmpeg \
            main.py

      - name: Zip TikTokConverter.app
        run: |
          cd dist
          zip -r TikTokConverter.app.zip TikTokConverter.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TikTokConverter.app
          path: dist/TikTokConverter.app.zip
