name: Build TikTokConverter.app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          check-latest: true

      - run: |
          brew update
          brew install tcl-tk ffmpeg

      - run: |
          python3 -m pip install --upgrade pip
          pip3 install py2app moviepy

      - name: Build .app with py2app
        run: python3 setup.py py2app

      - run: |
          codesign --force --deep --sign - dist/TikTokConverter.app

      - run: |
          ditto -c -k --sequesterRsrc --keepParent \
            dist/TikTokConverter.app TikTokConverter.app.zip

      - uses: actions/upload-artifact@v4
        with:
          name: TikTokConverter.app
          path: TikTokConverter.app.zip
