name: Build TikTokConverter.app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.11 (with tkinter)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          check-latest: true

      - name: Install system deps
        run: |
          brew update
          brew install tcl-tk ffmpeg

      - name: Install py2app & MoviePy
        run: |
          python3 -m pip install --upgrade pip
          pip install py2app moviepy

      - name: Build .app with py2app
        run: |
          # variantă A: dacă în setup.py ai 'standalone': True
          python3 setup.py py2app

          # sau, variantă B: forțezi semi-standalone
          # python3 setup.py py2app --semi-standalone

      - name: Codesign the .app
        run: |
          codesign --force --deep --sign - dist/TikTokConverter.app

      - name: Create ZIP via ditto
        run: |
          ditto -c -k --sequesterRsrc --keepParent \
            dist/TikTokConverter.app TikTokConverter.app.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TikTokConverter.app
          path: TikTokConverter.app.zip
