# .github/workflows/python-app.yml
name: Build TikTokConverter.app

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Miniforge (Conda)
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          auto-update-conda: true
          channels: conda-forge

      - name: Create & activate Conda env with Python, tk & ffmpeg
        shell: bash -l {0}
        run: |
          source "${CONDA}/etc/profile.d/conda.sh"
          conda create -y -n build-env python=3.11 tk ffmpeg
          conda activate build-env

      - name: Install Python deps in Conda env
        shell: bash -l {0}
        run: |
          conda activate build-env
          pip install --upgrade pip
          pip install moviepy pyinstaller

      - name: Build macOS .app with PyInstaller
        shell: bash -l {0}
        run: |
          conda activate build-env
          FFMPEG_PATH="$(which ffmpeg)"
          # clean any previous build
          pyinstaller \
            --clean \
            --noconfirm \
            --windowed \
            --name TikTokConverter \
            --add-binary "${FFMPEG_PATH}:ffmpeg" \
            --collect-submodules moviepy \
            --collect-submodules imageio \
            --collect-all imageio_ffmpeg \
            main.py

      - name: Zip TikTokConverter.app
        run: |
          cd dist
          zip -r TikTokConverter.app.zip TikTokConverter.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TikTokConverter.app
          path: dist/TikTokConverter.app.zip
