# .github/workflows/python-app.yml
name: Build TikTokConverter.app

on:
  push:        # rulează la orice push
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: List repo contents   # debug
      run: ls -R .

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install MoviePy & py2app
      run: |
        pip install --upgrade pip
        pip install moviepy py2app

    - name: Install ffmpeg
      run: brew install ffmpeg

    - name: Build .app with py2app
      run: python3 setup.py py2app

    - name: Zip TikTokConverter.app
      run: |
        cd dist
        zip -r TikTokConverter.app.zip TikTokConverter.app

    - uses: actions/upload-artifact@v4
      with:
        name: TikTokConverter.app
        path: dist/TikTokConverter.app.zip
